### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by lhstrh** [axmmisaka/lf-docs-docusaurus#5]

**Comment by axmmisaka** [comment]
Suppose LF blue and LF gold are derived from Berkeley's colour I recommend these colour palette:
![image](https://github.com/axmmisaka/lf-docs-docusaurus/assets/6500159/6f5aac0e-c6b3-4ad6-83df-b6be9969c73e)
This is based on the "founder's rock" colour; TUD also uses dark blue (Die Hausfarbe der TU Dresden ist Dunkelblau: https://tu-dresden.de/tu-dresden/kontakte-services/cd)) but idk how dark the blue is

This is based on a lighter version of berkeley blue called "lawrence" and we can use this as our dark mode colour:
![image](https://github.com/axmmisaka/lf-docs-docusaurus/assets/6500159/cb94e47a-2b0f-4b41-a06b-75bc609dd0cc)

**Comment by lhstrh** [comment]
I think this looks pretty good! Let's try it and see how it looks on the website?

**Comment by axmmisaka** [comment]
d661cbbfef571f07
